# stack yaml for ghc builds

resolver: lts-16.0

ghc-options: {"$locals": -funclutter-valid-hole-fits -fmax-relevant-binds=0}

extra-deps:
  # --- Missing from Stackage --- #
  - ed25519-donna-0.1.1
  - hspec-golden-0.1.0.2
  - direct-sqlite-2.3.26
  - sbv-8.8
  - megaparsec-9.0.0
  - neat-interpolation-0.5.1.2

  # --- Forced Downgrades --- #
  - prettyprinter-1.6.0         # >= 1.6.1 breaks bin compat in Chainweb blocks

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/pact-time.git
    commit: 4fe4b898f1d41823a30946a7d9c870b518ea4dc1
