# stack yaml for ghc builds

resolver: lts-14.18

extra-deps:
  # --- Missing from Stackage --- #
  - ed25519-donna-0.1.1
  - hspec-golden-0.1.0.1

  # --- Forced Downgrades --- #
  - sbv-8.2

  # --- Forced Upgrades --- #
  - trifecta-2.1
  - neat-interpolation-0.5.0.1

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
