# stack yaml for ghc builds

resolver: lts-15.4

ghc-options: {"$locals": -funclutter-valid-hole-fits -fmax-relevant-binds=0}

extra-deps:
  # --- Missing from Stackage --- #
  - ed25519-donna-0.1.1
  - hspec-golden-0.1.0.1
  - direct-sqlite-2.3.26
  - sbv-8.6

  # --- Forced Upgrades --- #
  - neat-interpolation-0.5.1

  # --- Forced Downgrades --- #
  - prettyprinter-1.6.0

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
