# stack yaml for ghc builds

resolver: lts-13.30

extra-deps:
  # --- Missing from Stackage --- #
  - ed25519-donna-0.1.1
  - prettyprinter-convert-ansi-wl-pprint-1.1

  # --- Forced Upgrades --- #
  - sbv-8.2

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
