name: Stack Build
on:
  pull_request:
  push:
    branches:
      - master
      - ci/*

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install non-Haskell dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zlib1g-dev libtinfo-dev libsqlite3-dev libz3-dev

      # currently broken
      # - name: Setup Z3
      #   uses: pavpanchekha/setup-z3@1.2.1
      #   with:
      #     version: "4.8.7"
      #     architecture: "x64"
      
      # use until setup-z3 is fixed
      - name: Install Z3
        run: |
          sudo apt-get update
          sudo apt-get install -y libz3-dev z3

      - name: Setup GHC
        uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.8.4"
          enable-stack: true
          stack-version: 'latest'

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack884-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack884-

      - name: Build
        run: "stack test --fast --no-terminal --system-ghc"
